// <auto-generated />
using System;
using LaCantine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaCantine.Migrations
{
    [DbContext(typeof(LaCantineContext))]
    [Migration("20220128104546_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaCantine.Model.Commandes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrixTotal")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("LaCantine.Model.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommandesID")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CommandesID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("LaCantine.Model.Plats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommandesID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuID")
                        .HasColumnType("int");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CommandesID");

                    b.HasIndex("MenuID");

                    b.ToTable("Plats");
                });

            modelBuilder.Entity("LaCantine.Model.Produits_Allergenes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlatsID")
                        .HasColumnType("int");

                    b.Property<string>("Produit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlatsID");

                    b.ToTable("Produits_Allergenes");
                });

            modelBuilder.Entity("LaCantine.Model.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Solde")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("LaCantine.Model.Commandes", b =>
                {
                    b.HasOne("LaCantine.Model.Utilisateur", null)
                        .WithMany("LesCommandes")
                        .HasForeignKey("UtilisateurId");
                });

            modelBuilder.Entity("LaCantine.Model.Menu", b =>
                {
                    b.HasOne("LaCantine.Model.Commandes", null)
                        .WithMany("LesMenus")
                        .HasForeignKey("CommandesID");
                });

            modelBuilder.Entity("LaCantine.Model.Plats", b =>
                {
                    b.HasOne("LaCantine.Model.Commandes", null)
                        .WithMany("LesPlats")
                        .HasForeignKey("CommandesID");

                    b.HasOne("LaCantine.Model.Menu", null)
                        .WithMany("LesPlats")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("LaCantine.Model.Produits_Allergenes", b =>
                {
                    b.HasOne("LaCantine.Model.Plats", null)
                        .WithMany("Produits_Allergenes")
                        .HasForeignKey("PlatsID");
                });

            modelBuilder.Entity("LaCantine.Model.Commandes", b =>
                {
                    b.Navigation("LesMenus");

                    b.Navigation("LesPlats");
                });

            modelBuilder.Entity("LaCantine.Model.Menu", b =>
                {
                    b.Navigation("LesPlats");
                });

            modelBuilder.Entity("LaCantine.Model.Plats", b =>
                {
                    b.Navigation("Produits_Allergenes");
                });

            modelBuilder.Entity("LaCantine.Model.Utilisateur", b =>
                {
                    b.Navigation("LesCommandes");
                });
#pragma warning restore 612, 618
        }
    }
}
